### PR TITLE
Migrate Objective-C code to Swift 

### PR DESCRIPTION
**Pull request by aaronsky**
This PR takes all Objective-C code in the ios folder and replaces it with a Swift analogue. It also adds some slight tweaks that were keeping the jsbundle from compiling that were addressed in #7 but never merged.

### CODE REVIEW

**Comment by HofmannZ** [comment]
Hi @aaronsky,

I really like Swift, but the code you just refactored is not actually from this repository, it's from [facebook/react-native](https://github.com/facebook/react-native). I would suggest you open a PR there ;)

**Comment by aaronsky** [comment]
I understand that, but I also don't think there's any harm in deviating from that.

**Comment by HofmannZ** [comment]
Well I assume the purpose of this repository is to help new developers get started with React Native and Typescript. Microsoft created a great guide to do so, if you follow along correctly you should end up with the same files as inside the repository. If you made a mistake you can use this repository as a reference.

The change you prepose will completely change that reference. Where the developer following the guide expects to see Objective-C code there now would be Swift code. This might cause the developer to think that is the cause of the issue and start changing it while there is no need for it.

Also unlike Objective-C, the Swift runtime is not bundled into iOS, therefore this change would also add a couple mb to the bundle size 😬.

**Comment by DanielRosenwasser** [comment]
I don't want to deviate from the output of the actual instructions listed in the README. If the React Native initialization script migrates to a Swift base project, we can baseline that output. Thanks for the PR though @aaronsky.

**Pull request closed without merging**
